# Generated by Django 2.0.5 on 2018-08-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180731_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Company_Email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='User_Email',
        ),
        migrations.AddField(
            model_name='company',
            name='Shared_Users',
            field=models.CharField(default='Current User only', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='Type_of_company',
            field=models.CharField(choices=[('Individual', 'Individual'), ('HUF', 'HUF'), ('Partnership', 'Partnership'), ('Trust', 'Trust'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('LLP', 'LLP')], default='Individual', max_length=32),
        ),
    ]
