# Generated by Django 2.0.6 on 2018-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180825_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Business_nature_Bonded_Warehouse',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='company',
            name='Business_nature_Factory_Manufacturing',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='company',
            name='Business_nature_Import',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='company',
            name='Business_nature_Leasing',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='company',
            name='Business_nature_Other',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='company',
            name='Business_nature_Retail',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='company',
            name='Business_nature_Service_Provider',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='company',
            name='Business_nature_Wholesale',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='company',
            name='Business_nature_Works_Contract',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='company',
            name='Please_specify',
            field=models.CharField(default=False, max_length=32),
            preserve_default=False,
        ),
    ]
