# Generated by Django 2.0.7 on 2018-08-21 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0002_auto_20180821_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ledger1',
            name='Creation_Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
