# Generated by Django 2.0.5 on 2018-08-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0004_auto_20180822_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Particulars',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_double_entry.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Particulars_Credit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creditledgers', to='accounting_double_entry.transaction'),
        ),
    ]
