# Generated by Django 2.0.5 on 2018-08-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0006_auto_20180822_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='Group',
        ),
    ]
