# Generated by Django 2.0.5 on 2018-08-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0007_remove_journal_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='Date',
        ),
    ]
