# Generated by Django 2.0.5 on 2018-08-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0010_auto_20180822_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='Particulars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debitledgers', to='accounting_double_entry.ledger1'),
        ),
    ]
