# Generated by Django 2.0.5 on 2018-08-25 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0011_auto_20180824_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
