# Generated by Django 2.0.5 on 2018-08-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0014_auto_20180825_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
