# Generated by Django 2.0.5 on 2018-08-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0015_auto_20180827_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='Particulars',
            new_name='By',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Particulars_Credit',
            new_name='To',
        ),
    ]
