# Generated by Django 2.0.5 on 2018-08-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0016_auto_20180828_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger1',
            name='Closing_Balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
