# Generated by Django 2.0.5 on 2018-08-28 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0017_ledger1_closing_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='Date',
        ),
        migrations.AddField(
            model_name='journal',
            name='_my_date',
            field=models.DateField(db_column='my_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
