# Generated by Django 2.0.5 on 2018-08-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0018_auto_20180828_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='total_debit',
        ),
    ]
