# Generated by Django 2.0.5 on 2018-08-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0019_auto_20180828_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger1',
            name='Total_Credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger1',
            name='Total_Debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
