# Generated by Django 2.0.5 on 2018-08-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0021_auto_20180828_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger1',
            name='Closing_Balance',
        ),
    ]
