# Generated by Django 2.0.5 on 2018-08-28 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0022_remove_ledger1_closing_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='_my_date',
        ),
        migrations.AddField(
            model_name='journal',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
