# Generated by Django 2.0.5 on 2018-08-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0025_ledger1_closing_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Closing_Balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_double_entry.ledger1')),
            ],
        ),
    ]
