# Generated by Django 2.0.5 on 2018-09-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0026_c_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='Total_Credit',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='Total_Debit',
        ),
    ]
