# Generated by Django 2.0.5 on 2018-09-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0027_auto_20180901_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger1',
            name='Closing_Balance',
        ),
    ]
