# Generated by Django 2.0.5 on 2018-09-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0028_remove_ledger1_closing_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_balance',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='c_balance',
        ),
    ]
