# Generated by Django 2.0.7 on 2018-07-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Double_entryy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='balance_nature',
            field=models.CharField(max_length=32),
        ),
    ]
