# Generated by Django 2.0.7 on 2018-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Double_entryy', '0002_auto_20180718_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='balance_nature',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Not Applicable', 'Not Applicable')], default='Debit', max_length=32),
        ),
    ]
