# Generated by Django 2.0.7 on 2018-08-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('double_entry', '0002_auto_20180731_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group1',
            old_name='Nature_of_group1',
            new_name='Nature_of_group',
        ),
        migrations.RenameField(
            model_name='ledger1',
            old_name='group1_Name',
            new_name='group_Name',
        ),
    ]
