# Generated by Django 2.0.7 on 2018-08-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('double_entry', '0004_auto_20180801_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group1',
            old_name='Nature_of_group',
            new_name='Nature_of_group1',
        ),
        migrations.RenameField(
            model_name='ledger1',
            old_name='group_Name',
            new_name='group1_Name',
        ),
    ]
