# Generated by Django 2.0.7 on 2018-08-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('double_entry', '0006_auto_20180801_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger1',
            name='group1_Name',
        ),
        migrations.DeleteModel(
            name='ledger1',
        ),
    ]
